### ISSUE TITLE
Talk proposal

### ISSUE THREAD

**Issue by stefan-reich** [scala-hamburg/scala-hamburg#16]
Hi, I make an interesting operating system based on a Java dialect.

Chance for a talk? :)

Greetings,
Stefan
BotCompany.de

**Comment by magro** [comment]
On Wednesday we discussed the idea of lightning talks, so that everybody can talk 10 or 15 minutes about s.th. he'd like to discuss, introduce to others, or get feedback to. Maybe that would be a good fit?

For a "regular" talk proposal you might share a bit more details in order to increase the probability to get thumbsups from others. The title could also be more specific :-)

**Comment by lutzh** [comment]
It doesn't sound like a good fit, and it has been dorment for a year.. so I'm closing it. Please re-open if you disagree.

**Comment by stefan-reich** [comment]
"It doesn't sound like a good fit" is just sad.... this is computer science of general interest.

Sure, I'd still be open to do a lightning talk.

**Comment by lutzh** [comment]
> this is computer science of general interest

But then why do you think this is the right meetup for your talk? After all it's not the "Computer Science General Interest Meetup", it's a community of Scala developers, interested in talking about Scala-related topics. What's the connection between your talk and the Scala programming language? Why is it interesting specifically to Scala developers?
